"""Typed authoring records and deterministic compilation; no combinatorial expansion."""
from typing import Literal

from pydantic import Field

from character_performance.domain.models import DomainModel, FacialAction, NonEmptyId, PerformanceUnit
from character_performance.ontology.emotion import EmotionOntology


class CatalogRecord(DomainModel):
    id: NonEmptyId
    category: Literal["facial", "gaze", "micro_expression", "body", "spatial", "physiology", "speech", "world_specific"]
    channel: NonEmptyId
    parts: tuple[NonEmptyId, ...]
    family: NonEmptyId
    meaning: str = Field(min_length=6)
    clause: str = Field(min_length=3)
    emotions: tuple[NonEmptyId, ...] = Field(min_length=2, max_length=6)
    axis: Literal["initiative", "withdrawal", "self_control", "aggression", "warmth", "tension", "deference"]
    facts: tuple[NonEmptyId, ...] = ()
    preconditions: tuple[NonEmptyId, ...] = ()
    effects: dict = Field(default_factory=dict)
    capabilities: tuple[NonEmptyId, ...] = ()
    visibility: Literal["very_subtle", "subtle", "noticeable", "obvious"] = "subtle"
    world: dict = Field(default_factory=dict)
    facial_actions: tuple[FacialAction, ...] = ()
    intensity: tuple[float, float] = (.15, .95)


def compile_record(record: CatalogRecord, ontology: EmotionOntology) -> PerformanceUnit:
    if len(set(record.emotions)) != len(record.emotions):
        raise ValueError(f"duplicate emotion affinity: {record.id}")
    # Distinct records are authored, never generated by parameter products.
    affinities = {label: .86 if index == 0 else .7 for index, label in enumerate(record.emotions)}
    prototypes = {label: ontology.resolve(label).prototype_vad if label != "calm" else None for label in affinities}
    vad = {axis: round(sum((getattr(prototypes[label], axis) if prototypes[label] else {"valence": .2, "arousal": -.5, "dominance": .3}[axis]) * weight for label, weight in affinities.items()) / sum(affinities.values()), 4) for axis in ("valence", "arousal", "dominance")}
    capabilities = set(record.capabilities)
    preconditions = set(record.preconditions)
    for fact in record.facts:
        if fact.startswith("held."):
            parts = fact.split(".", 2)
            if len(parts) != 3 or parts[1] not in {"left", "right", "both"}:
                raise ValueError(f"invalid held fact: {record.id}: {fact}")
            for side in (("left", "right") if parts[1] == "both" else (parts[1],)):
                preconditions.add(f"{side}_hand_holding")
    if record.category == "gaze":
        capabilities.add("vision")
    if record.category == "speech":
        capabilities.add("speech")
    if "对方" in record.clause:
        preconditions.add("target_known")
    for side in ("left", "right"):
        if f"{side}_hand" in record.parts or "hands" in record.parts:
            capabilities.add(f"{side}_hand_use")
            if f"{side}_hand_holding" not in preconditions:
                preconditions.add(f"{side}_hand_free")
    physical = {"capabilities": sorted(capabilities)}
    if "distance_delta" in record.effects or record.effects.get("pose") == "standing":
        capabilities.add("walking")
        physical.update(capabilities=sorted(capabilities), min_mobility=.5)
    if record.category == "speech":
        physical["min_breath"] = .15
    extra = {}
    if record.category == "micro_expression":
        if not record.facial_actions:
            raise ValueError(f"micro expression without anatomical trajectory: {record.id}")
        extra.update(timing={"onset_ms": [40, 90], "apex_ms": [40, 100], "offset_ms": [80, 210], "total_duration_ms": [160, 400]})
    return PerformanceUnit(id=record.id, category=record.category, channel=record.channel,
        atomic_action=record.id.split(".", 1)[1], body_parts=record.parts,
        semantic_groups={record.family}, semantics={record.axis: .8},
        emotion_affinity=affinities, intensity_range={"min": record.intensity[0], "max": record.intensity[1]},
        context_requirements={"required_facts": list(record.facts)} if record.facts else {},
        physical_requirements=physical, preconditions=tuple(sorted(preconditions)), effects=record.effects,
        visibility="very_subtle" if record.category == "micro_expression" else record.visibility,
        narrative_weight=.48, cooldown={"turns": 6}, repeat_group=record.family,
        render_hints={"subject": "", "verb": record.clause, "complement": ""},
        source_refs=("src.original.catalog.v1",), license_class="original", status="active",
        vad_affinity=vad, facial_units=record.facial_actions, world_requirements=record.world,
        description_zh=record.meaning, **extra)
